-- HAYYAK Seed Data
-- Run AFTER schema.sql
-- Replace the password hash below with one generated by:
--   php -r "echo password_hash('YourAdminPassword', PASSWORD_BCRYPT, ['cost'=>12]);"

SET NAMES utf8mb4;

-- Default admin user (password: Admin@Hayyak2024 — CHANGE THIS)
INSERT IGNORE INTO `users`
  (`email`, `password_hash`, `role`, `name_en`, `name_ar`, `language`)
VALUES
  (
    'admin@hayyak.ae',
    '$2y$12$placeholder.replace.this.with.real.bcrypt.hash.xxxxx',
    'admin',
    'Admin',
    'المسؤول',
    'ar'
  );
